/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as LightningRouteImport } from './routes/lightning'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as FlashDealsRouteImport } from './routes/flash-deals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const LightningRoute = LightningRouteImport.update({
  id: '/lightning',
  path: '/lightning',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashDealsRoute = FlashDealsRouteImport.update({
  id: '/flash-deals',
  path: '/flash-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/flash-deals': typeof FlashDealsRoute
  '/itineraries': typeof ItinerariesRoute
  '/lightning': typeof LightningRoute
  '/nearby': typeof NearbyRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/weather': typeof WeatherRoute
  '/activity/$id': typeof ActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/flash-deals': typeof FlashDealsRoute
  '/itineraries': typeof ItinerariesRoute
  '/lightning': typeof LightningRoute
  '/nearby': typeof NearbyRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/weather': typeof WeatherRoute
  '/activity/$id': typeof ActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/auth': typeof AuthRoute
  '/flash-deals': typeof FlashDealsRoute
  '/itineraries': typeof ItinerariesRoute
  '/lightning': typeof LightningRoute
  '/nearby': typeof NearbyRoute
  '/partner': typeof PartnerRoute
  '/profile': typeof ProfileRoute
  '/weather': typeof WeatherRoute
  '/activity/$id': typeof ActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/flash-deals'
    | '/itineraries'
    | '/lightning'
    | '/nearby'
    | '/partner'
    | '/profile'
    | '/weather'
    | '/activity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/flash-deals'
    | '/itineraries'
    | '/lightning'
    | '/nearby'
    | '/partner'
    | '/profile'
    | '/weather'
    | '/activity/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/auth'
    | '/flash-deals'
    | '/itineraries'
    | '/lightning'
    | '/nearby'
    | '/partner'
    | '/profile'
    | '/weather'
    | '/activity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AuthRoute: typeof AuthRoute
  FlashDealsRoute: typeof FlashDealsRoute
  ItinerariesRoute: typeof ItinerariesRoute
  LightningRoute: typeof LightningRoute
  NearbyRoute: typeof NearbyRoute
  PartnerRoute: typeof PartnerRoute
  ProfileRoute: typeof ProfileRoute
  WeatherRoute: typeof WeatherRoute
  ActivityIdRoute: typeof ActivityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lightning': {
      id: '/lightning'
      path: '/lightning'
      fullPath: '/lightning'
      preLoaderRoute: typeof LightningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash-deals': {
      id: '/flash-deals'
      path: '/flash-deals'
      fullPath: '/flash-deals'
      preLoaderRoute: typeof FlashDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  AuthRoute: AuthRoute,
  FlashDealsRoute: FlashDealsRoute,
  ItinerariesRoute: ItinerariesRoute,
  LightningRoute: LightningRoute,
  NearbyRoute: NearbyRoute,
  PartnerRoute: PartnerRoute,
  ProfileRoute: ProfileRoute,
  WeatherRoute: WeatherRoute,
  ActivityIdRoute: ActivityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
